language: java
jdk:
  - oraclejdk9
  - oraclejdk8
install: mvn -s .travis.maven.settings.xml install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn -s .travis.maven.settings.xml verify -Pdist
matrix:
  include:
  # Tomcat 9.x targets
  - jdk: oraclejdk9
    script: mvn verify -s .travis.maven.settings.xml -PTC9 -Pdist
  - jdk: oraclejdk8
    script: mvn verify -s .travis.maven.settings.xml -PTC9 -Pdist
notifications:
  email: false
