language: java
jdk:
  - openjdk10
  - openjdk8
matrix:
  include:
    # Tomcat 9.x targets
    - jdk: openjdk10
      script: mvn verify -PTC9 -Pdist
    - jdk: openjdk8
      script: mvn verify -PTC9 -Pdist
notifications:
  email: false
