os: linux
dist: trusty
language: java
before_install: wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
script: ./mvnw verify -B && ./mvnw verify -PTC9 -B
jobs:
  include:
    # JDK 8
    - env: JDK_RELEASE='OracleJDK 8'
      jdk: oraclejdk8
    - env: JDK_RELEASE='OpenJDK 8'
      jdk: openjdk8
    # JDK 9
    - env: JDK_RELEASE='OracleJDK 9'
      jdk: oraclejdk9
#    - env: JDK_RELEASE='OpenJDK 9'
#      install: . ./install-jdk.sh -F 9
#    # JDK 10
#    - env: JDK_RELEASE='OracleJDK 10'
#      install: . ./install-jdk.sh -F 10
#    - env: JDK_RELEASE='OpenJDK 10'
#      install: . ./install-jdk.sh -F 10
    # JDK 11
    - env: JDK_RELEASE='OracleJDK 11'
      install: . ./install-jdk.sh -F 11 -L BCL
    - env: JDK_RELEASE='OpenJDK 11'
      install: . ./install-jdk.sh -F 11 -L GPL
    # JDK 12
    - env: JDK_RELEASE='OracleJDK 12'
      install: . ./install-jdk.sh -F 12
    - env: JDK_RELEASE='OpenJDK 12'
      install: . ./install-jdk.sh -F 12
    # JDK 13
    - env: JDK_RELEASE='OracleJDK 13'
      install: . ./install-jdk.sh -F 13
    - env: JDK_RELEASE='OpenJDK 13'
      install: . ./install-jdk.sh -F 13
    # JDK 14
    - env: JDK_RELEASE='OracleJDK 14'
      install: . ./install-jdk.sh -F 14
    - env: JDK_RELEASE='OpenJDK 14'
      install: . ./install-jdk.sh -F 14
notifications:
  email: false
